### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by DRB02** [abramkremer/supreme-monitor#2]
Hey I really like your monitor. 
Could you please add that it shares links aswell and not only a picture and the name?

Thank you!
greetings,
Dylan (DRB02)

**Comment by ghost** [comment]
> Hey I really like your monitor.
> Could you please add that it shares links aswell and not only a picture and the name?
> 
> Thank you!
> greetings,
> Dylan (DRB02)

With a little tweaking on the source code, you can generate a link. Essentially all you need to do is get the item's id and go to https://www.supremenewyork.com/shop/id.

**Comment by abramkremer** [comment]
> Hey I really like your monitor.
> Could you please add that it shares links aswell and not only a picture and the name?
> 
> Thank you!
> greetings,
> Dylan (DRB02)

Hey, just added the product links to the embed notifications. Enjoy!
