### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by BrandonHowe** [abramkremer/supreme-monitor#3]
Hi, I made a bot similar to this for my own use. However, it seems like Supreme blocks many IP addresses (namely DigitalOcean, Heroku, and some VPN's) so it is hard to get a 24/7 hosting. What hosting platform do you use to host this?

**Comment by abramkremer** [comment]
Supreme will not allow the majority of popular server IPs to access stock information. Running locally during drop time will work best.
